const DAYS=[
{k:'lunes',s:'Lun',t:'Pecho + hombro + tríceps',e:[E('press-inclinado','Press inclinado en multipower',2,'6–10','3–4 min'),E('press-plano-l','Press plano en máquina',2,'8–12','2:30–3 min'),E('pec-deck-l','Pec deck',3,'10–15','1:30–2 min'),E('press-militar','Press militar',2,'6–10','3 min'),E('lateral-l','Elevación lateral unilateral en polea con tobillera',3,'12–20','1:30–2 min',1),E('triceps-triangulo','Tríceps en polea con cuerda',3,'8–12','1:30–2 min'),E('triceps-overhead-l','Extensión de tríceps por encima de la cabeza',2,'10–15','1:30–2 min')]},
{k:'martes',s:'Mar',t:'Espalda + bíceps + deltoide posterior',e:[E('jalon-pecho','Jalón al pecho en máquina',2,'6–10','2:30–3 min'),E('d-low-row','D Low Row',2,'8–12','2:30–3 min'),E('remo','Remo',2,'8–12','2:30–3 min'),E('posterior-m','Hombro posterior en polea unilateral con tobillera',3,'12–20','1:30–2 min',1),E('predicador-m','Predicador unilateral en máquina',3,'8–12','1:30–2 min',1),E('martillo-m','Curl martillo',2,'8–12','1:30–2 min')]},
{k:'miercoles',s:'Mié',t:'Pierna + abdominales',e:[E('pendular','Sentadilla pendular',2,'6–10','3–4 min'),E('prensa','Prensa',2,'8–12','3 min'),E('extension-cuad','Extensión de cuádriceps',3,'10–15','1:30–2 min'),E('femoral','Curl femoral',4,'8–15','1:30–2 min'),E('abductores','Abductores en máquina',3,'12–20','1:30–2 min'),E('gemelo','Gemelos',3,'8–15','1:30–2 min'),E('abs-m','Abdominales',3,'10–20','1–2 min')]},
{k:'jueves',s:'Jue',t:'Pecho + espalda + hombro',e:[E('press-plano-j','Press plano en máquina',2,'8–12','2:30–3 min'),E('pec-deck-j','Pec deck',3,'10–15','1:30–2 min'),E('jalon-cerrado','Jalón cerrado / neutro',2,'8–12','2:30–3 min'),E('pullover','Pullover',3,'10–15','1:30–2 min'),E('lateral-j','Elevación lateral unilateral en polea',3,'12–20','1:30–2 min',1),E('posterior-j','Hombro posterior en polea unilateral con tobillera',2,'12–20','1:30–2 min',1)]},
{k:'viernes',s:'Vie',t:'Bíceps + tríceps + abdominales',e:[E('barra-z','Curl con barra Z',3,'8–12','1:30–2 min'),E('bayesian','Bayesian curl',3,'10–15','1:30–2 min'),E('martillo-v','Curl martillo',2,'8–12','1:30–2 min'),E('triceps-uni','Tríceps unilateral en polea con tobillera',3,'8–12','1:30–2 min',1),E('triceps-overhead-v','Extensión de tríceps por encima de la cabeza',3,'10–15','1:30–2 min'),E('abs-v','Abdominales',3,'10–20','1–2 min')]}
];
function E(id,n,set,r,rest,u){return{id:id,n:n,set:set,r:r,rest:rest,u:!!u}}
const KEY='rutina_gym_pages_v1';
function emptySet(u){return u?{R:{kg:'',rep:''},L:{kg:'',rep:''}}:{kg:'',rep:''}}
function emptyWeek(){const x={};DAYS.forEach(d=>{x[d.k]={};d.e.forEach(e=>x[d.k][e.id]=Array.from({length:e.set},()=>emptySet(e.u))) });return x}
function normSet(s,u){if(!s)return emptySet(u);if(u){if(s.R||s.L)return{R:{kg:s.R?.kg||'',rep:s.R?.rep||s.R?.reps||''},L:{kg:s.L?.kg||'',rep:s.L?.rep||s.L?.reps||''}};return{R:{kg:s.kg||'',rep:s.rep||s.reps||''},L:{kg:s.kg||'',rep:s.rep||s.reps||''}}}return{kg:s.kg||'',rep:s.rep||s.reps||''}}
function normWeek(w){const x=emptyWeek();DAYS.forEach(d=>d.e.forEach(e=>{const a=w?.[d.k]?.[e.id]||[];x[d.k][e.id]=Array.from({length:e.set},(_,i)=>normSet(a[i],e.u))}));return x}
function load(){try{const a=JSON.parse(localStorage.getItem(KEY)||'null');return a?{current:normWeek(a.current),history:(a.history||[]).map(w=>({...w,data:normWeek(w.data)}))}:{current:emptyWeek(),history:[]}}catch(e){return{current:emptyWeek(),history:[]}}}
let state=load(),tab=defaultDay(),editing=null,draft=null;
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function defaultDay(){const a=['domingo','lunes','martes','miercoles','jueves','viernes','sabado'],k=a[new Date().getDay()];return DAYS.some(d=>d.k===k)?k:'lunes'}
function nextWeek(){return state.history.reduce((m,w)=>Math.max(m,w.number||0),0)+1}
function data(){return editing?draft:state.current}
function previous(){const a=state.history.filter(w=>!editing||w.number<editing).sort((x,y)=>x.number-y.number);return a.length?a[a.length-1]:null}
function h(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){document.getElementById('modeSub').textContent=editing?'Editando Semana '+editing:'Semana en curso';document.getElementById('weekPill').textContent='Semana '+(editing||nextWeek());document.getElementById('editBar').classList.toggle('hidden',!editing);renderNav();const d=DAYS.find(x=>x.k===tab);if(d)renderDay(d);else if(tab==='hist')renderHistory();else renderMore()}
function renderNav(){const n=document.getElementById('nav');n.innerHTML='';DAYS.forEach(d=>navBtn(n,d.k,d.s,'▣'));navBtn(n,'hist','Hist.','◷');navBtn(n,'more','Más','⋯')}
function navBtn(n,k,t,i){const b=document.createElement('button');b.className=tab===k?'active':'';b.innerHTML='<span>'+i+'</span>'+t;b.onclick=()=>{tab=k;render()};n.appendChild(b)}
function inp(d,e,i,side,f,v,ph){return '<input class="field" type="number" inputmode="'+(f==='kg'?'decimal':'numeric')+'" step="'+(f==='kg'?'.5':'1')+'" placeholder="'+ph+'" value="'+h(v)+'" data-d="'+d+'" data-e="'+e+'" data-i="'+i+'" data-side="'+side+'" data-f="'+f+'">'}
function renderDay(d){const m=document.getElementById('main'),w=data(),p=previous();m.innerHTML='<h2 class="day-title">'+d.k.charAt(0).toUpperCase()+d.k.slice(1)+'</h2><div class="day-sub">'+d.t+'</div>'+(p?'<div class="lastweek"><strong>Referencia: Semana '+p.number+'</strong><span>Intenta igualar o superar peso o repeticiones.</span></div>':'');d.e.forEach((e,ix)=>{const c=document.createElement('section');c.className='card';let s='<div class="head"><div class="num">'+(ix+1)+'</div><div><div class="name">'+e.n+(e.u?'<span class="badge">UNILATERAL</span>':'')+'</div><div class="meta">'+e.set+' series · '+e.r+' reps · descanso '+e.rest+'</div></div></div><div class="sets">';w[d.k][e.id].forEach((set,i)=>{const old=p?.data?.[d.k]?.[e.id]?.[i];if(e.u){s+='<div class="uni"><div class="unitop"><span>Serie '+(i+1)+'</span><span>'+e.r+' reps</span></div><div class="side"><label class="l">Izquierda</label>'+inp(d.k,e.id,i,'L','kg',set.L.kg,'kg')+inp(d.k,e.id,i,'L','rep',set.L.rep,'reps')+'</div><div class="side"><label class="r">Derecha</label>'+inp(d.k,e.id,i,'R','kg',set.R.kg,'kg')+inp(d.k,e.id,i,'R','rep',set.R.rep,'reps')+'</div>'+(old?'<div class="prev"><strong>Semana '+p.number+'</strong> · I: '+(old.L?.kg||'–')+' kg × '+(old.L?.rep||'–')+' · D: '+(old.R?.kg||'–')+' kg × '+(old.R?.rep||'–')+'</div>':'')+'</div>'}else{s+='<div class="setrow"><div class="setlab">S'+(i+1)+'</div>'+inp(d.k,e.id,i,'','kg',set.kg,'kg')+inp(d.k,e.id,i,'','rep',set.rep,'reps')+'</div>'+(old?'<div class="prev"><strong>Semana '+p.number+'</strong> · S'+(i+1)+': '+(old.kg||'–')+' kg × '+(old.rep||'–')+'</div>':'')}});s+='</div>';c.innerHTML=s;m.appendChild(c)});m.insertAdjacentHTML('beforeend','<p class="note">Compuestos grandes: fallo técnico. Aislamientos: puedes llegar al fallo muscular si mantienes una ejecución limpia.</p>');m.querySelectorAll('input[data-d]').forEach(x=>x.addEventListener('input',changeInput))}
function changeInput(ev){const x=ev.target,w=data(),s=w[x.dataset.d][x.dataset.e][+x.dataset.i];if(x.dataset.side)s[x.dataset.side][x.dataset.f]=x.value;else s[x.dataset.f]=x.value;if(!editing)save()}
function renderHistory(){const m=document.getElementById('main');m.innerHTML='<h2 class="section">Historial</h2>';if(!state.history.length){m.innerHTML+='<div class="empty">Todavía no has guardado ninguna semana.</div>';return}[...state.history].sort((a,b)=>b.number-a.number).forEach(w=>{const c=document.createElement('div');c.className='card';c.innerHTML='<div class="name">Semana '+w.number+'</div><div class="meta">'+count(w.data)+' series registradas'+(w.savedAt?' · '+new Date(w.savedAt).toLocaleDateString('es-ES'):'')+'</div><div class="actions"><button class="btn primary edit">Editar semana</button><button class="btn danger del">Borrar semana</button></div>';c.querySelector('.edit').onclick=()=>beginEdit(w.number);c.querySelector('.del').onclick=()=>askDelete(w.number);m.appendChild(c)})}
function renderMore(){const m=document.getElementById('main');m.innerHTML='<h2 class="section">Más</h2><div class="card"><div class="name">Cerrar semana</div><div class="meta">Archiva esta semana y empieza una nueva vacía.</div><button id="archive" class="btn primary full">Guardar semana y empezar otra</button></div><div class="card"><div class="name">Copia de seguridad</div><div class="meta">Exporta o restaura todos tus datos.</div><div class="actions"><button id="export" class="btn secondary">Exportar</button><button id="import" class="btn secondary">Importar</button></div><input id="file" class="file" type="file" accept="application/json"></div><div class="card"><div class="name">Rutina Gym</div><div class="meta">Los datos se guardan automáticamente en este navegador.</div></div>';document.getElementById('archive').onclick=askArchive;document.getElementById('export').onclick=exportData;document.getElementById('import').onclick=()=>document.getElementById('file').click();document.getElementById('file').onchange=e=>importData(e.target.files[0])}
function askArchive(){if(editing)return;modal('¿Guardar semana y empezar otra?','Se archivará como Semana '+nextWeek()+' y empezarás una nueva vacía.','Sí, guardar',archiveWeek)}
function archiveWeek(){const n=nextWeek();state.history.push({number:n,data:normWeek(state.current),savedAt:new Date().toISOString()});state.current=emptyWeek();save();closeModal();showToast('Semana '+n+' guardada');tab='lunes';render()}
function beginEdit(n){const w=state.history.find(x=>x.number===n);if(!w)return;editing=n;draft=normWeek(w.data);tab='lunes';render()}
function saveEdit(){const i=state.history.findIndex(x=>x.number===editing);if(i>=0)state.history[i]={...state.history[i],data:normWeek(draft)};const n=editing;editing=null;draft=null;save();tab='hist';showToast('Semana '+n+' actualizada');render()}
function cancelEdit(){editing=null;draft=null;tab='hist';render()}
function askDelete(n){modal('¿Borrar Semana '+n+'?','Esta acción no se puede deshacer.','Sí, borrar',()=>{state.history=state.history.filter(x=>x.number!==n);save();closeModal();showToast('Semana '+n+' eliminada');render()},1)}
function modal(title,text,ok,fn,danger){const x=document.getElementById('modal');x.innerHTML='<div class="modalwrap"><div class="modal"><h3>'+title+'</h3><p>'+text+'</p><div class="actions"><button id="mc" class="btn secondary">Cancelar</button><button id="mo" class="btn '+(danger?'danger':'primary')+'">'+ok+'</button></div></div></div>';document.getElementById('mc').onclick=closeModal;document.getElementById('mo').onclick=fn}
function closeModal(){document.getElementById('modal').innerHTML=''}
function exportData(){const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='rutina-gym-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);showToast('Copia exportada')}
async function importData(f){if(!f)return;try{const x=JSON.parse(await f.text());state={current:normWeek(x.current),history:(x.history||[]).map(w=>({...w,data:normWeek(w.data)}))};save();showToast('Copia importada');render()}catch(e){showToast('Archivo no válido')}}
function count(w){let n=0;DAYS.forEach(d=>d.e.forEach(e=>(w[d.k]?.[e.id]||[]).forEach(s=>{if(e.u){if(s.R?.kg||s.R?.rep||s.L?.kg||s.L?.rep)n++}else if(s.kg||s.rep)n++})));return n}
function showToast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.remove('hidden');clearTimeout(showToast._t);showToast._t=setTimeout(()=>x.classList.add('hidden'),1800)}
document.getElementById('cancelEditBtn').onclick=cancelEdit;document.getElementById('saveEditBtn').onclick=saveEdit;render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));